// Parameters loaded from models/*.bin (generated by scripts/export_params_bin.py).
// Layouts mirror the Python SDK (community1_sdk).
#pragma once

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

static inline std::vector<float> read_f32(const std::string& path) {
    FILE* f = fopen(path.c_str(), "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", path.c_str()); exit(1); }
    fseek(f, 0, SEEK_END);
    long n = ftell(f) / 4;
    fseek(f, 0, SEEK_SET);
    std::vector<float> v(n);
    if (fread(v.data(), 4, n, f) != (size_t)n) { fprintf(stderr, "read fail %s\n", path.c_str()); exit(1); }
    fclose(f);
    return v;
}

static inline std::vector<int32_t> read_i32(const std::string& path, int count) {
    FILE* f = fopen(path.c_str(), "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", path.c_str()); exit(1); }
    std::vector<int32_t> v(count);
    if (fread(v.data(), 4, count, f) != (size_t)count) { fprintf(stderr, "read fail %s\n", path.c_str()); exit(1); }
    fclose(f);
    return v;
}

struct Params {
    // fbank
    int win_size = 400, win_shift = 160, padded = 512;
    std::vector<float> window;      // (400)
    std::vector<float> mel_banks;   // (257, 80) k-major
    // frontend (InstanceNorm weights)
    float norm_w = 0, norm_b = 0;
    std::vector<float> n0w, n0b, n1w, n1b, n2w, n2b;   // 80/80/60/60/60/60
    // ffn
    std::vector<float> l0w, l0b, l1w, l1b, cw, cb;     // (256,128)(128)(128,128)(128)(128,7)(7)
    // powerset
    std::vector<float> mapping;     // (7,3)
    // embedding tail
    int n_frames = 125, n_weights = 589, feats = 2560;
    std::vector<float> seg1_w, seg1_b;  // (256, 5120), (256)
    // plda
    std::vector<float> mean1, mean2, lda, plda_mu, plda_tr, plda_psi;

    void Load(const std::string& model_dir) {
        auto fb_i = read_i32(model_dir + "/fbank.bin", 3);
        win_size = fb_i[0]; win_shift = fb_i[1]; padded = fb_i[2];
        auto fb = read_f32(model_dir + "/fbank.bin");
        size_t off = 3 * 4 / 4;  // skip the 3 int32 read as floats
        // fbank.bin = 3 int32 + 400 floats + 80*513 floats
        size_t w_off = (3 * 4) / 4;
        window.assign(fb.begin() + w_off, fb.begin() + w_off + win_size);
        {   // transpose mel (80, 257) -> (257, 80) k-major
            const float* src = fb.data() + w_off + win_size;
            mel_banks.resize(257 * 80);
            for (int k = 0; k < 257; ++k)
                for (int b = 0; b < 80; ++b) mel_banks[k * 80 + b] = src[b * 257 + k];
        }

        auto fe = read_f32(model_dir + "/frontend.bin");
        norm_w = fe[0]; norm_b = fe[1];
        size_t p = 2;
        n0w.assign(fe.begin() + p, fe.begin() + p + 80); p += 80;
        n0b.assign(fe.begin() + p, fe.begin() + p + 80); p += 80;
        n1w.assign(fe.begin() + p, fe.begin() + p + 60); p += 60;
        n1b.assign(fe.begin() + p, fe.begin() + p + 60); p += 60;
        n2w.assign(fe.begin() + p, fe.begin() + p + 60); p += 60;
        n2b.assign(fe.begin() + p, fe.begin() + p + 60); p += 60;

        auto ff = read_f32(model_dir + "/ffn.bin");
        p = 0;
        l0w.assign(ff.begin(), ff.begin() + 256 * 128);   // (i, o) i-major
        p += 256 * 128;
        l0b.assign(ff.begin() + p, ff.begin() + p + 128); p += 128;
        l1w.assign(ff.begin() + p, ff.begin() + p + 128 * 128); p += 128 * 128;
        l1b.assign(ff.begin() + p, ff.begin() + p + 128); p += 128;
        cw.assign(ff.begin() + p, ff.begin() + p + 128 * 7); p += 128 * 7;
        cb.assign(ff.begin() + p, ff.begin() + p + 7); p += 7;

        mapping = read_f32(model_dir + "/powerset.bin");

        auto ei = read_i32(model_dir + "/embtail.bin", 3);
        n_frames = ei[0]; n_weights = ei[1]; feats = ei[2];
        auto et = read_f32(model_dir + "/embtail.bin");
        size_t e_off = 3 * 4 / 4;
        {   // transpose seg1 to (i, o) i-major for rank-1 GEMM
            seg1_w.resize(256 * 5120);
            const float* src = et.data() + e_off;   // (o, i) = (256, 5120)
            for (int o = 0; o < 256; ++o)
                for (int i = 0; i < 5120; ++i) seg1_w[i * 256 + o] = src[o * 5120 + i];
        }
        seg1_b.assign(et.begin() + e_off + 256 * 5120, et.end());

        auto pl = read_f32(model_dir + "/plda.bin");
        p = 0;
        mean1.assign(pl.begin(), pl.begin() + 256); p += 256;
        mean2.assign(pl.begin() + p, pl.begin() + p + 128); p += 128;
        lda.assign(pl.begin() + p, pl.begin() + p + 256 * 128); p += 256 * 128;
        plda_mu.assign(pl.begin() + p, pl.begin() + p + 128); p += 128;
        plda_tr.assign(pl.begin() + p, pl.begin() + p + 128 * 128); p += 128 * 128;
        plda_psi.assign(pl.begin() + p, pl.begin() + p + 256);
    }
};
